@startuml
'https://plantuml.com/class-diagram
title:单例模式

class HeroAircraft {
    - shootNum:int
    - power:int
    - direction:int
    - {static} HeroAircraft:heroAircraft
    + {static} HeroAircraft(int locationX, int locationY, int speedX, int speedY, int hp)
    + getInstance(int locationX, int locationY, int speedX, int speedY, int hp):HeroAircraft
    + forward():void
    + shoot():List<BaseBullet>
    + increaseHp(int increase):void
}

HeroAircraft <-- HeroAircraft
HeroAircraft <-- game

@enduml